const fs=require('fs'),vm=require('vm'),assert=require('assert');
for(const file of ['index.html','index_operator.html']){
const s=fs.readFileSync(file,'utf8');const names=['creditVerifiedDocument','creditDocumentModelItems','creditStatementMeta','creditMovementMeta','creditMovementType','creditMovementNeedsClassification','creditStatementSystemMovements','creditSumSystem','creditTaxCode','creditDollarPerceptionCode','creditCurrentStatementPayments','creditUsdPaymentDecision','creditPaymentStatus','creditPaymentModel','roundMoney'];
const code=names.map(n=>{const a=s.indexOf('function '+n+'(');assert(a>=0,n);return s.slice(a,s.indexOf('\n}',a)+2);}).join('\n');const c={CREDIT_META_PREFIX:'[[CREDIT_META:',CREDIT_STATEMENT_META_PREFIX:'[[CREDIT_STATEMENT_META:'};vm.createContext(c);vm.runInContext(code,c);
const components=[{category:'purchase',description:'Total consumos',amountArs:143869.01,amountUsd:463.48},{category:'tax',description:'IMPUESTO DE SELLOS',amountArs:1726.43,amountUsd:5.56},{category:'tax',description:'PERCEPCION IVA',amountArs:147310.17},{category:'tax',description:'PERCEP.AFIP RG 4815',amountArs:210443.08},{category:'tax',description:'PERC IIBB',amountArs:14029.54},{category:'carried_balance',description:'Saldo anterior',amountArs:-44550.05}];
const st={total_ars:472828.18,total_usd:469.04,notes:'[[CREDIT_STATEMENT_META:'+JSON.stringify({documentFinancials:{version:1,components,totals:{statementArs:472828.18,calculatedArs:472828.18,statementUsd:469.04,calculatedUsd:469.04}}})+']]'};
const payment={description:'Pago en USD',currency:'USD',amount:469.04,notes:'[[CREDIT_META:{"movementType":"payment","source":"manual_payment"}]]'};let model=c.creditPaymentModel(st,[payment]);assert.equal(model.dollarPerception,210443.08);assert.equal(Math.round(model.remainingArs*100)/100,262385.10);assert.equal(model.paidUsd,469.04);assert.equal(model.ivaPerception,147310.17);assert.equal(model.sellosUsd,5.56);
model=c.creditPaymentModel(st,[]);assert.equal(model.remainingArs,472828.18);assert.equal(model.remainingUsd,469.04);
model=c.creditPaymentModel(st,[payment,{description:'PERCEP.AFIP RG 4815',currency:'ARS',amount:210443.08}]);assert.equal(model.dollarPerception,210443.08);
assert.equal(c.creditVerifiedDocument({...st,total_ars:99}),null);console.log(file+': 9 pruebas de calculo documental correctas');}
